import type { Customer } from "@/lib/customers/types";

/**
 * Mock customer dataset for Sprint 2. Chosen to produce a realistic spread of
 * readiness bands and protection statuses (some protected, some nearly ready,
 * some unprotected) so every surface that consumes Readiness can be exercised.
 * No business logic produces these — replaced by repository reads later.
 */
export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "CUS-2041",
    fullName: "Thandi Mokoena",
    email: "thandi.mokoena@example.co.za",
    mobile: "+27 82 555 0141",
    location: "Johannesburg",
    joinedAt: "2026-01-12T08:00:00.000Z",
    profileComplete: true,
    identityStatus: "PENDING",
    emergencyInfoComplete: true,
    emergencyContactsCount: 2,
    cardStatus: "NONE",
  },
  {
    id: "CUS-2042",
    fullName: "Sipho Dlamini",
    email: "sipho.dlamini@example.co.za",
    mobile: "+27 83 555 0142",
    location: "Durban",
    joinedAt: "2026-02-03T08:00:00.000Z",
    profileComplete: true,
    identityStatus: "VERIFIED",
    emergencyInfoComplete: true,
    emergencyContactsCount: 1,
    cardStatus: "PENDING",
  },
  {
    id: "CUS-2043",
    fullName: "Aisha Patel",
    email: "aisha.patel@example.co.za",
    location: "Cape Town",
    joinedAt: "2025-11-20T08:00:00.000Z",
    profileComplete: true,
    identityStatus: "VERIFIED",
    emergencyInfoComplete: true,
    emergencyContactsCount: 3,
    cardStatus: "ACTIVE",
  },
  {
    id: "CUS-2044",
    fullName: "Grace Mahlangu",
    email: "grace.mahlangu@example.co.za",
    location: "Pretoria",
    joinedAt: "2026-06-25T08:00:00.000Z",
    profileComplete: false,
    identityStatus: "UNVERIFIED",
    emergencyInfoComplete: false,
    emergencyContactsCount: 0,
    cardStatus: "NONE",
  },
  {
    id: "CUS-2045",
    fullName: "Bongani Zulu",
    email: "bongani.zulu@example.co.za",
    location: "Soweto",
    joinedAt: "2026-03-15T08:00:00.000Z",
    profileComplete: true,
    identityStatus: "PENDING",
    emergencyInfoComplete: true,
    emergencyContactsCount: 1,
    cardStatus: "NONE",
  },
  {
    id: "CUS-2046",
    fullName: "Fatima Adams",
    email: "fatima.adams@example.co.za",
    location: "Cape Town",
    joinedAt: "2025-10-08T08:00:00.000Z",
    profileComplete: true,
    identityStatus: "VERIFIED",
    emergencyInfoComplete: true,
    emergencyContactsCount: 2,
    cardStatus: "ACTIVE",
  },
  {
    id: "CUS-2047",
    fullName: "Themba Ndlovu",
    email: "themba.ndlovu@example.co.za",
    location: "Bloemfontein",
    joinedAt: "2026-06-28T08:00:00.000Z",
    profileComplete: true,
    identityStatus: "UNVERIFIED",
    emergencyInfoComplete: false,
    emergencyContactsCount: 1,
    cardStatus: "NONE",
  },
  {
    id: "CUS-2048",
    fullName: "Kabelo Sithole",
    email: "kabelo.sithole@example.co.za",
    location: "Polokwane",
    joinedAt: "2026-04-22T08:00:00.000Z",
    profileComplete: true,
    identityStatus: "VERIFIED",
    emergencyInfoComplete: false,
    emergencyContactsCount: 1,
    cardStatus: "PENDING",
  },
  {
    id: "CUS-2049",
    fullName: "Lindiwe Khumalo",
    email: "lindiwe.khumalo@example.co.za",
    location: "Durban",
    joinedAt: "2025-09-30T08:00:00.000Z",
    profileComplete: true,
    identityStatus: "VERIFIED",
    emergencyInfoComplete: true,
    emergencyContactsCount: 2,
    cardStatus: "ACTIVE",
  },
  {
    id: "CUS-2050",
    fullName: "Andile Mbeki",
    email: "andile.mbeki@example.co.za",
    location: "Gqeberha",
    joinedAt: "2026-05-18T08:00:00.000Z",
    profileComplete: true,
    identityStatus: "VERIFIED",
    emergencyInfoComplete: true,
    emergencyContactsCount: 0,
    cardStatus: "SUSPENDED",
  },
];

export function getCustomer(id: string): Customer | undefined {
  return MOCK_CUSTOMERS.find((c) => c.id === id);
}
